/RMG/Geometry/RegisterDetector Germanium V99000A 001

/run/initialize

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume Source

/RMG/Output/Germanium/StoreTrackID
/RMG/Output/Germanium/Cluster/PreClusterOutputs
/RMG/Output/Germanium/Cluster/CombineLowEnergyElectronTracks
/RMG/Output/Germanium/Cluster/RedistributeGammaEnergy
/RMG/Output/Germanium/Cluster/PreClusterDistance 1 mm

/RMG/Generator/Select GPS
/gps/particle gamma
/gps/ang/type iso
/gps/energy 1000 keV

/run/beamOn 1000
